//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmdcLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmdcLauncher.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// </summary>
        public static string AboutDevoted {
            get {
                return ResourceManager.GetString("AboutDevoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is provided &quot;AS IS&quot; without any warranties. Author isn&apos;t responsible for any damage caused by application usage.
        /// </summary>
        public static string AboutNotice {
            get {
                return ResourceManager.GetString("AboutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, note:.
        /// </summary>
        public static string AboutPleaseNote {
            get {
                return ResourceManager.GetString("AboutPleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying security settings....
        /// </summary>
        public static string ApplyingSecuritySettings {
            get {
                return ResourceManager.GetString("ApplyingSecuritySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string btnDisable {
            get {
                return ResourceManager.GetString("btnDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        public static string CopyingFiles {
            get {
                return ResourceManager.GetString("CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoreCon IPs:.
        /// </summary>
        public static string CoreConIPs {
            get {
                return ResourceManager.GetString("CoreConIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string HomeAbout {
            get {
                return ResourceManager.GetString("HomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Launch&quot; to run Windows Mobile Device Center phone client..
        /// </summary>
        public static string InfoClickToRun {
            get {
                return ResourceManager.GetString("InfoClickToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience any problems with application debugging, click &quot;Disable&quot; and reconnect the phone to your PC..
        /// </summary>
        public static string InfoDebuggingProblems {
            get {
                return ResourceManager.GetString("InfoDebuggingProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Microsoft Visual Studio 2008 for native application debugging or Microsoft Visual Studio 2010/2012 for silverlight application debugging..
        /// </summary>
        public static string InfoDebuggingRun {
            get {
                return ResourceManager.GetString("InfoDebuggingRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Windows Mobile Device Center on your PC to get an access to your device files..
        /// </summary>
        public static string InfoInstallWmdcOnPc {
            get {
                return ResourceManager.GetString("InfoInstallWmdcOnPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem instanciating native code.
        /// </summary>
        public static string InstanciatingNativeCode {
            get {
                return ResourceManager.GetString("InstanciatingNativeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Mobile Device Center trademark is a property of Microsoft Corporation. .
        /// </summary>
        public static string MsProperty {
            get {
                return ResourceManager.GetString("MsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IPs. Are you using custom transport?.
        /// </summary>
        public static string NoIPs {
            get {
                return ResourceManager.GetString("NoIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application doesn&apos;t have a root access to your device. Make sure you have full unlocked ROM..
        /// </summary>
        public static string NoRootAccess {
            get {
                return ResourceManager.GetString("NoRootAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering COM dll....
        /// </summary>
        public static string RegisteringComDll {
            get {
                return ResourceManager.GetString("RegisteringComDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem registering com dll.
        /// </summary>
        public static string RegisteringComDllProblem {
            get {
                return ResourceManager.GetString("RegisteringComDllProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start debugger automatically.
        /// </summary>
        public static string StartDebuggerAutomatically {
            get {
                return ResourceManager.GetString("StartDebuggerAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Connection Manager....
        /// </summary>
        public static string StartingConnectionManager {
            get {
                return ResourceManager.GetString("StartingConnectionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured while creating Connection Manager.
        /// </summary>
        public static string StartingConnectionManagerProblem {
            get {
                return ResourceManager.GetString("StartingConnectionManagerProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting RAPI worker....
        /// </summary>
        public static string StartingRapiWorker {
            get {
                return ResourceManager.GetString("StartingRapiWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured while creating RAPI worker.
        /// </summary>
        public static string StartingRapiWorkerProblem {
            get {
                return ResourceManager.GetString("StartingRapiWorkerProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start WMDC automatically.
        /// </summary>
        public static string StartWmdcAutomatically {
            get {
                return ResourceManager.GetString("StartWmdcAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger isn&apos;t running.
        /// </summary>
        public static string StateDebuggerDisabled {
            get {
                return ResourceManager.GetString("StateDebuggerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger is being disabled....
        /// </summary>
        public static string StateDebuggerDisabling {
            get {
                return ResourceManager.GetString("StateDebuggerDisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger is running.
        /// </summary>
        public static string StateDebuggerEnabled {
            get {
                return ResourceManager.GetString("StateDebuggerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string StateDisabled {
            get {
                return ResourceManager.GetString("StateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string StateEnabled {
            get {
                return ResourceManager.GetString("StateEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling....
        /// </summary>
        public static string StateEnabling {
            get {
                return ResourceManager.GetString("StateEnabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string StateFailed {
            get {
                return ResourceManager.GetString("StateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System integration.
        /// </summary>
        public static string SystemIntegration {
            get {
                return ResourceManager.GetString("SystemIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate to make WMDC running at startup..
        /// </summary>
        public static string SystemIntegrationInfo {
            get {
                return ResourceManager.GetString("SystemIntegrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating processes....
        /// </summary>
        public static string TerminatingProcesses {
            get {
                return ResourceManager.GetString("TerminatingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use VS debugger from PC.
        /// </summary>
        public static string UsePcDebugger {
            get {
                return ResourceManager.GetString("UsePcDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for IP resolving.
        /// </summary>
        public static string WaitingForIpResolving {
            get {
                return ResourceManager.GetString("WaitingForIpResolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Mobile Device Center Launcher.
        /// </summary>
        public static string WmdcLauncher {
            get {
                return ResourceManager.GetString("WmdcLauncher", resourceCulture);
            }
        }
    }
}
